src/java/server/entity/Brukere.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package server.entity;

import java.io.Serializable;
import java.util.Collection;
import java.util.logging.Logger;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Mikael
 */
@Entity
@Table(name = "Brukere")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Brukere.findAll", query = "SELECT b FROM Brukere b"),
    @NamedQuery(name = "Brukere.findByIdBrukere", query = "SELECT b FROM Brukere b WHERE b.idBrukere = :idBrukere"),
    @NamedQuery(name = "Brukere.findByBrukernavn", query = "SELECT b FROM Brukere b WHERE b.brukernavn = :brukernavn"),
    @NamedQuery(name = "Brukere.findByFornavn", query = "SELECT b FROM Brukere b WHERE b.fornavn = :fornavn"),
    @NamedQuery(name = "Brukere.findByEtternavn", query = "SELECT b FROM Brukere b WHERE b.etternavn = :etternavn"),
    @NamedQuery(name = "Brukere.findByPassord", query = "SELECT b FROM Brukere b WHERE b.passord = :passord")})
public class Brukere implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "idBrukere")
    private Integer idBrukere;
    @Size(max = 45)
    @Column(name = "Brukernavn")
    private String brukernavn;
    @Size(max = 45)
    @Column(name = "Fornavn")
    private String fornavn;
    @Size(max = 45)
    @Column(name = "Etternavn")
    private String etternavn;
    @Size(max = 45)
    @Column(name = "Passord")
    private String passord;
    @OneToMany(mappedBy = "montertavfk", fetch = FetchType.LAZY, cascade={CascadeType.MERGE, CascadeType.PERSIST})
    private Collection<Beslagslister> beslagslisterCollection;
    @ManyToMany(mappedBy = "brukereCollection", fetch = FetchType.LAZY, cascade={CascadeType.MERGE, CascadeType.PERSIST})
    private Collection<Prosjekter> prosjekterCollection;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "Version")
    private Double version;

    public Double getVersion() {
        return version;
    }

    public void setVersion(Double version) {
        this.version = version;
    }

    public Brukere() {
    }
    
    @XmlTransient
    public Collection<Prosjekter> getProsjekterCollection() {
        return prosjekterCollection;
    }

    public void setProsjekterCollection(Collection<Prosjekter> prosjekterCollection) {
        this.prosjekterCollection = prosjekterCollection;
    }
    
    public void addProsjekter(Prosjekter prosjekt){
        this.prosjekterCollection.add(prosjekt);
    }
    
    public void removeProsjekter(Prosjekter prosjekt){
        this.prosjekterCollection.remove(prosjekt);
    }

    public Brukere(Integer idBrukere) {
        this.idBrukere = idBrukere;
    }

    public Integer getIdBrukere() {
        return idBrukere;
    }

    public void setIdBrukere(Integer idBrukere) {
        this.idBrukere = idBrukere;
    }

    public String getFornavn() {
        return fornavn;
    }

    public void setFornavn(String fornavn) {
        this.fornavn = fornavn;
    }

    public String getEtternavn() {
        return etternavn;
    }

    public void setEtternavn(String etternavn) {
        this.etternavn = etternavn;
    }

    public String getBrukernavn() {
        return brukernavn;
    }

    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }

    public String getPassord() {
        return passord;
    }

    public void setPassord(String passord) {
        this.passord = passord;
    }

    @XmlTransient
    public Collection<Beslagslister> getBeslagslisterCollection() {
        return beslagslisterCollection;
    }

    public void setBeslagslisterCollection(Collection<Beslagslister> beslagslisterCollection) {
        this.beslagslisterCollection = beslagslisterCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idBrukere != null ? idBrukere.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Brukere)) {
            return false;
        }
        Brukere other = (Brukere) object;
        if ((this.idBrukere == null && other.idBrukere != null) || (this.idBrukere != null && !this.idBrukere.equals(other.idBrukere))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return brukernavn;
    }
    private static final Logger LOG = Logger.getLogger(Brukere.class.getName());



    
}

src/java/server/web/ProsjekterController.java
package server.web;

import java.io.Serializable;
import java.util.Iterator;
import java.util.List;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.primefaces.context.RequestContext;
import org.primefaces.model.LazyDataModel;
import server.ejb.ProsjekterFacade;
import server.entity.Brukere;
import server.entity.KontaktPersoner;
import server.entity.Prosjekter;
import server.web.util.JsfUtil;
import server.web.util.PaginationHelper;
import server.web.util.SerializableListDataModel;

/**
 *
 * @author
 * Mikael
 */
@ManagedBean(name = "prosjekterController")
@SessionScoped
public class ProsjekterController implements Serializable {

    private Prosjekter current;
    private SerializableListDataModel items = null;
    @EJB
    private server.ejb.ProsjekterFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private List<Prosjekter> filteredProsjekter;
//    private LazyDataModel<Prosjekter> lazyModel;
/*
     public LazyDataModel<Prosjekter> getLazyModel() {
     List<Prosjekter> prosjekter = ejbFacade.findAll();
     lazyModel = new LazyProsjekterDataModel(prosjekter);
     return lazyModel;
     }
     */

    public List<Prosjekter> getFilteredProsjekter() {
        return filteredProsjekter;
    }

    public void setFilteredProsjekter(List<Prosjekter> filteredProsjekter) {
        this.filteredProsjekter = filteredProsjekter;
    }

    /**
     *
     */
    public ProsjekterController() {
    }

    /**
     * Returnerer
     * det
     * valgte
     * objektet
     * fra
     * JSF
     * filen.
     * Hvis
     * Objetet
     * er
     * null
     * opprettes
     * et
     * nytt
     * Objekt
     * og
     * selecetedItemIndex
     * settes
     * til
     * den
     * ugyldige
     * verdien
     * -1.
     *
     * @return
     * current,
     * Det
     * valgte
     * Prosjekter
     * objektet
     * eller
     * ett
     * nytt
     * Prosjekter
     * objekt
     */
    public Prosjekter getSelected() {
        if (current == null) {
//            current = new Prosjekter();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ProsjekterFacade getFacade() {
        return ejbFacade;
    }

    /**
     *
     * @return
     */
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(1000) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public SerializableListDataModel createPageDataModel() {
                    return new SerializableListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    /**
     *
     * @return
     */
    public String prepareList() {
        recreateModel();
        return "/prosjekter/List";
    }

    /**
     *
     * @return
     */
    public String prepareView() {
        current = (Prosjekter) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/prosjekter/View";
    }

    /**
     *
     * @return
     */
    public String prepareNewView(Prosjekter prosjekt) {
        current = prosjekt;
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/prosjekter/View";
    }

    /**
     *
     * @return
     */
    public String prepareCreate() {
        current = new Prosjekter();
        selectedItemIndex = -1;
        return "/prosjekter/Create";
    }

    /**
     *
     * @return
     */
    public String create() {
        try {
            getFacade().create(current);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterCreated")));
            return prepareCreate();
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Database: ", ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured") + " " + e));

            return null;
        }
    }

    /**
     *
     * @return
     */
    public String prepareEdit() {
        current = (Prosjekter) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/prosjekter/Edit";
    }

    public void addKontaktPerson(KontaktPersoner kontaktperson) {
        if (!current.getKontaktPersonerCollection().contains(kontaktperson)) {
            current.addKontaktPersoner(kontaktperson);
            kontaktperson.addProsjekter(current);
            try {
                getFacade().editKontaktPerson(kontaktperson);
                getFacade().edit(current);
                recreateModel();
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterUpdated")));
            } catch (Exception e) {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Database: ", ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured") + " " + e));
            }
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterKontaktPersonerFinnes")));
        }
    }

    public void removeFromProject(KontaktPersoner kontaktperson, Prosjekter prosjekt) {
        kontaktperson.removeProsjekter(prosjekt);
        prosjekt.removeKontaktPersoner(kontaktperson);
        try {
            getFacade().edit(prosjekt);
            getFacade().editKontaktPerson(kontaktperson);
            recreateModel();
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterUpdated")));
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Database: ", ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured")));
        }
    }

    public void addBruker(Brukere bruker) {
        if (!current.getBrukereCollection().contains(bruker)) {
            current.addBrukere(bruker);
            bruker.addProsjekter(current);
            try {
                getFacade().editBrukere(bruker);
                getFacade().edit(current);
                recreateModel();
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterUpdated")));
            } catch (Exception e) {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Database: ", ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured") + " " + e));
            }
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterBrukerFinnes")));
        }
    }

    public void removeBruker(Brukere bruker) {
        if (current.getBrukereCollection().contains(bruker)) {
            current.removeBrukere(bruker);
            bruker.removeProsjekter(current);
            try {
                getFacade().editBrukere(bruker);
                getFacade().edit(current);
                recreateModel();
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterUpdated")));
            } catch (Exception e) {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Database: ", ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured") + " " + e));
            }
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Database: ", ResourceBundle.getBundle("/Bundle").getString("ProsjekterBrukerFinnesIkke")));
        }
    }

    /**
     *
     * @return
     */
    public String update() {
        try {
            try {
                getFacade().edit(current);
            } catch (ConstraintViolationException ex) {
                Set<ConstraintViolation<?>> violation = ex.getConstraintViolations();
                String violations = "";
                for (Iterator it = violation.iterator(); it.hasNext();) {
                    String viol = (String) it.next();
                    violations += viol + "\n";
                }
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Database: ", violations));
                Logger.getLogger(ProsjekterController.class.getName()).log(Level.SEVERE, null, ex);
            }

web/brukere/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateBrukereTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateBrukereLabel_idBrukere}" for="idBrukere" />
                    <h:inputText id="idBrukere" value="#{brukereController.selected.idBrukere}" title="#{bundle.CreateBrukereTitle_idBrukere}" required="true" requiredMessage="#{bundle.CreateBrukereRequiredMessage_idBrukere}"/>
                    <h:outputLabel value="#{bundle.CreateBrukereLabel_brukernavn}" for="brukernavn" />
                    <h:inputText id="brukernavn" value="#{brukereController.selected.brukernavn}" title="#{bundle.CreateBrukereTitle_brukernavn}" />
                    <h:outputLabel value="#{bundle.CreateBrukereLabel_passord}" for="passord" />
                    <h:inputText id="passord" value="#{brukereController.selected.passord}" title="#{bundle.CreateBrukereTitle_passord}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{brukereController.create}" value="#{bundle.CreateBrukereSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{brukereController.prepareList}" value="#{bundle.CreateBrukereShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateBrukereIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/brukere/CreateBruker.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:body>   
        <h:panelGroup styleClass="dialogForm" layout="block">
            <h:form>
                <header>
                    <h2>
                        <h:outputText value="#{bundle.BrukereCreate}"></h:outputText>
                    </h2>
                </header>
                <p:growl id="growl" showDetail="true" sticky="true" />
                <p:panelGrid columns="2" id="CreateDialog">
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_brukernavn}" for="brukernavn" />
                    <h:inputText id="brukernavn" value="#{brukereController.selected.brukernavn}" title="#{bundle.BrukereTitle_brukernavn}" />
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_fornavn}" for="fornavn" />
                    <h:inputText id="fornavn" value="#{brukereController.selected.fornavn}" 
                                 title="#{bundle.BrukereTitle_fornavn}" />
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_etternavn}" for="etternavn" />
                    <h:inputText id="etternavn" value="#{brukereController.selected.etternavn}" 
                                 title="#{bundle.BrukereTitle_etternavn}" />
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_passord}" for="passord" />
                    <p:password id="passord" maxlength="8" required="true" requiredMessage="#{bundle.PassordObligatorisk}" 
                                value="#{brukereController.nyttPass}"/>
                    <h:outputLabel value="#{bundle.BrukereLabel_passord_control}" for="passord_control" />
                    <p:password id="passord_control"  required="true" requiredMessage="#{bundle.PassordObligatorisk}" 
                                value="#{brukereController.nyttPassKontroll}"/>
                </p:panelGrid>
                <p:commandButton value="#{bundle.SaveLink}"
                                 update=":brukerForm"
                                 id="submitButton"                                
                                 action="#{brukereController.createDialog}"
                                 title="Lagre"
                                 />
                
                
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/brukere/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditBrukereTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditBrukereLabel_idBrukere}" for="idBrukere" />
                    <h:inputText id="idBrukere" value="#{brukereController.selected.idBrukere}" title="#{bundle.EditBrukereTitle_idBrukere}" required="true" requiredMessage="#{bundle.EditBrukereRequiredMessage_idBrukere}"/>
                    <h:outputLabel value="#{bundle.EditBrukereLabel_brukernavn}" for="brukernavn" />
                    <h:inputText id="brukernavn" value="#{brukereController.selected.brukernavn}" title="#{bundle.EditBrukereTitle_brukernavn}" />
                    <h:outputLabel value="#{bundle.EditBrukereLabel_passord}" for="passord" />
                    <h:inputText id="passord" value="#{brukereController.selected.passord}" title="#{bundle.EditBrukereTitle_passord}" />
                </h:panelGrid>
                <h:commandLink action="#{brukereController.update}" value="#{bundle.EditBrukereSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditBrukereViewLink}"/>
                <br />
                <h:commandLink action="#{brukereController.prepareList}" value="#{bundle.EditBrukereShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditBrukereIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/brukere/EditBruker.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <h:panelGroup styleClass="editDialogForm" layout="block">
            <h:form >
                <header>
                    <h2>
                        <h:outputText></h:outputText>
                    </h2>
                </header>
                <h:panelGrid columns="2" id="editDialog" cellpadding="4">
                    <h:outputLabel value="#{bundle.BrukereLabel_idBrukere}" for="idBrukere" />
                    <h:inputText id="idBrukere" value="#{brukereController.selected.idBrukere}" 
                                 title="#{bundle.BrukereTitle_idBrukere}" required="true" 
                                 requiredMessage="#{bundle.EditBrukereRequiredMessage_idBrukere}" disabled="true"/>
                    <h:outputLabel value="#{bundle.BrukereLabel_brukernavn}" for="brukernavn" />
                    <h:inputText id="brukernavn" value="#{brukereController.selected.brukernavn}" 
                                 title="#{bundle.BrukereTitle_brukernavn}" />
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_fornavn}" for="fornavn" />
                    <h:inputText id="fornavn" value="#{brukereController.selected.fornavn}" 
                                 title="#{bundle.BrukereTitle_fornavn}" />
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_etternavn}" for="etternavn" />
                    <h:inputText id="etternavn" value="#{brukereController.selected.etternavn}" 
                                 title="#{bundle.BrukereTitle_etternavn}" />
                    
                    <h:outputLabel value="#{bundle.BrukereLabel_passord}" for="gammeltPassord" />
                    <p:password id="gammeltPassord" required="true" requiredMessage="#{bundle.PassordObligatorisk}" 
                                value="#{brukereController.gammeltPass}"/>
                    <h:outputLabel value="#{bundle.BrukereLabel_nyttPassord}" for="nyttPassord" />
                    <p:password id="nyttPassord" required="false" value="#{brukereController.nyttPass}"/>
                    <h:outputLabel value="#{bundle.BrukereLabel_passord_control}" for="passord_control" />
                    <p:password id="passord_control"  required="false" value="#{brukereController.nyttPassKontroll}"/>
                    
                </h:panelGrid>
                <p:commandButton value="#{bundle.SaveLink}"
                                 update=":brukere"
                                 id="submitButton"                                
                                 action="#{brukereController.updateDialog}"
                                 oncomplete="editBrukerDlg.hide();"
                                 />
                
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/brukere/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.BrukereTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <ui:include src="table.xhtml"></ui:include>
        </ui:define>
    </ui:composition>

</html>

web/brukere/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewBrukereTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewBrukereLabel_idBrukere}"/>
                    <h:outputText value="#{brukereController.selected.idBrukere}" title="#{bundle.ViewBrukereTitle_idBrukere}"/>
                    <h:outputText value="#{bundle.ViewBrukereLabel_brukernavn}"/>
                    <h:outputText value="#{brukereController.selected.brukernavn}" title="#{bundle.ViewBrukereTitle_brukernavn}"/>
                    <h:outputText value="#{bundle.ViewBrukereLabel_passord}"/>
                    <h:outputText value="#{brukereController.selected.passord}" title="#{bundle.ViewBrukereTitle_passord}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{brukereController.destroyAndView}" value="#{bundle.ViewBrukereDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewBrukereEditLink}"/>
                <br />
                <h:commandLink action="#{brukereController.prepareCreate}" value="#{bundle.ViewBrukereCreateLink}" />
                <br />
                <h:commandLink action="#{brukereController.prepareList}" value="#{bundle.ViewBrukereShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewBrukereIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>