src/java/server/entity/ProsjektKategorier.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package server.entity;

import java.io.Serializable;
import java.util.Collection;
import java.util.logging.Logger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Mikael
 */
@Entity
@Table(name = "ProsjektKategorier")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "ProsjektKategorier.findAll", query = "SELECT p FROM ProsjektKategorier p"),
    @NamedQuery(name = "ProsjektKategorier.findByIdProsjektKategorier", query = "SELECT p FROM ProsjektKategorier p WHERE p.idProsjektKategorier = :idProsjektKategorier"),
    @NamedQuery(name = "ProsjektKategorier.findByKategoriNavn", query = "SELECT p FROM ProsjektKategorier p WHERE p.kategoriNavn = :kategoriNavn"),
    @NamedQuery(name = "ProsjektKategorier.findByVersion", query = "SELECT p FROM ProsjektKategorier p WHERE p.version > :version")})
public class ProsjektKategorier implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    
    @Column(name = "idProsjektKategorier")
    private Integer idProsjektKategorier;
    @Size(max = 45)
    @Column(name = "KategoriNavn")
    private String kategoriNavn;
    @OneToMany(mappedBy = "prosjektKategorieridProsjektKategorier", fetch = FetchType.LAZY)
    private Collection<Prosjekter> prosjekterCollection;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "Version")
    private Double version;

    public Double getVersion() {
        return version;
    }

    public void setVersion(Double version) {
        this.version = version;
    }

    public ProsjektKategorier() {
    }

    public ProsjektKategorier(Integer idProsjektKategorier) {
        this.idProsjektKategorier = idProsjektKategorier;
    }

    public Integer getIdProsjektKategorier() {
        return idProsjektKategorier;
    }

    public void setIdProsjektKategorier(Integer idProsjektKategorier) {
        this.idProsjektKategorier = idProsjektKategorier;
    }

    public String getKategoriNavn() {
        return kategoriNavn;
    }

    public void setKategoriNavn(String kategoriNavn) {
        this.kategoriNavn = kategoriNavn;
    }

    @XmlTransient
    public Collection<Prosjekter> getProsjekterCollection() {
        return prosjekterCollection;
    }

    public void setProsjekterCollection(Collection<Prosjekter> prosjekterCollection) {
        this.prosjekterCollection = prosjekterCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idProsjektKategorier != null ? idProsjektKategorier.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof ProsjektKategorier)) {
            return false;
        }
        ProsjektKategorier other = (ProsjektKategorier) object;
        if ((this.idProsjektKategorier == null && other.idProsjektKategorier != null) || (this.idProsjektKategorier != null && !this.idProsjektKategorier.equals(other.idProsjektKategorier))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return kategoriNavn;
    }
    private static final Logger LOG = Logger.getLogger(ProsjektKategorier.class.getName());
    
}

src/java/server/web/ProsjektKategorierController.java
package server.web;

import java.io.Serializable;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import server.ejb.ProsjektKategorierFacade;
import server.entity.ProsjektKategorier;
import server.web.util.JsfUtil;
import server.web.util.PaginationHelper;
import server.web.util.SerializableListDataModel;

@ManagedBean(name = "prosjektKategorierController")
@SessionScoped
public class ProsjektKategorierController implements Serializable {

    private ProsjektKategorier current;
    private DataModel items = null;
    @EJB
    private server.ejb.ProsjektKategorierFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public ProsjektKategorierController() {
    }

    public ProsjektKategorier getSelected() {
        if (current == null) {
            current = new ProsjektKategorier();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ProsjektKategorierFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public SerializableListDataModel createPageDataModel() {
                    return new SerializableListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "/prosjektKategorier/List";
    }

    public String prepareView() {
        current = (ProsjektKategorier) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/prosjektKategorier/View";
    }

    public String prepareCreate() {
        current = new ProsjektKategorier();
        selectedItemIndex = -1;
        return "/prosjektKategorier/Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ProsjektKategorierCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (ProsjektKategorier) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/prosjektKategorier/Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ProsjektKategorierUpdated"));
            return "/prosjektKategorier/View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (ProsjektKategorier) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "/prosjektKategorier/List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "/prosjektKategorier/View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "/prosjektKategorier/List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ProsjektKategorierDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "/prosjektKategorier/List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "/prosjektKategorier/List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = ProsjektKategorier.class)
    public static class ProsjektKategorierControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ProsjektKategorierController controller = (ProsjektKategorierController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "prosjektKategorierController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof ProsjektKategorier) {
                ProsjektKategorier o = (ProsjektKategorier) object;
                return getStringKey(o.getIdProsjektKategorier());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + ProsjektKategorier.class.getName());
            }
        }
    }
    private static final Logger LOG = Logger.getLogger(ProsjektKategorierController.class.getName());
}

web/prosjektKategorier/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateProsjektKategorierTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateProsjektKategorierLabel_idProsjektKategorier}" for="idProsjektKategorier" />
                    <h:inputText id="idProsjektKategorier" value="#{prosjektKategorierController.selected.idProsjektKategorier}" title="#{bundle.CreateProsjektKategorierTitle_idProsjektKategorier}" required="true" requiredMessage="#{bundle.CreateProsjektKategorierRequiredMessage_idProsjektKategorier}"/>
                    <h:outputLabel value="#{bundle.CreateProsjektKategorierLabel_kategoriNavn}" for="kategoriNavn" />
                    <h:inputText id="kategoriNavn" value="#{prosjektKategorierController.selected.kategoriNavn}" title="#{bundle.CreateProsjektKategorierTitle_kategoriNavn}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{prosjektKategorierController.create}" value="#{bundle.CreateProsjektKategorierSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{prosjektKategorierController.prepareList}" value="#{bundle.CreateProsjektKategorierShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateProsjektKategorierIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/prosjektKategorier/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditProsjektKategorierTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditProsjektKategorierLabel_idProsjektKategorier}" for="idProsjektKategorier" />
                    <h:inputText id="idProsjektKategorier" value="#{prosjektKategorierController.selected.idProsjektKategorier}" title="#{bundle.EditProsjektKategorierTitle_idProsjektKategorier}" required="true" requiredMessage="#{bundle.EditProsjektKategorierRequiredMessage_idProsjektKategorier}"/>
                    <h:outputLabel value="#{bundle.EditProsjektKategorierLabel_kategoriNavn}" for="kategoriNavn" />
                    <h:inputText id="kategoriNavn" value="#{prosjektKategorierController.selected.kategoriNavn}" title="#{bundle.EditProsjektKategorierTitle_kategoriNavn}" />
                </h:panelGrid>
                <h:commandLink action="#{prosjektKategorierController.update}" value="#{bundle.EditProsjektKategorierSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditProsjektKategorierViewLink}"/>
                <br />
                <h:commandLink action="#{prosjektKategorierController.prepareList}" value="#{bundle.EditProsjektKategorierShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditProsjektKategorierIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/prosjektKategorier/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListProsjektKategorierTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListProsjektKategorierEmpty}" rendered="#{prosjektKategorierController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{prosjektKategorierController.items.rowCount > 0}">
                    <h:outputText value="#{prosjektKategorierController.pagination.pageFirstItem + 1}..#{prosjektKategorierController.pagination.pageLastItem + 1}/#{prosjektKategorierController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{prosjektKategorierController.previous}" value="#{bundle.Previous} #{prosjektKategorierController.pagination.pageSize}" rendered="#{prosjektKategorierController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{prosjektKategorierController.next}" value="#{bundle.Next} #{prosjektKategorierController.pagination.pageSize}" rendered="#{prosjektKategorierController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{prosjektKategorierController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProsjektKategorierTitle_idProsjektKategorier}"/>
                            </f:facet>
                            <h:outputText value="#{item.idProsjektKategorier}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProsjektKategorierTitle_kategoriNavn}"/>
                            </f:facet>
                            <h:outputText value="#{item.kategoriNavn}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{prosjektKategorierController.prepareView}" value="#{bundle.ListProsjektKategorierViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{prosjektKategorierController.prepareEdit}" value="#{bundle.ListProsjektKategorierEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{prosjektKategorierController.destroy}" value="#{bundle.ListProsjektKategorierDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{prosjektKategorierController.prepareCreate}" value="#{bundle.ListProsjektKategorierCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListProsjektKategorierIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/prosjektKategorier/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewProsjektKategorierTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewProsjektKategorierLabel_idProsjektKategorier}"/>
                    <h:outputText value="#{prosjektKategorierController.selected.idProsjektKategorier}" title="#{bundle.ViewProsjektKategorierTitle_idProsjektKategorier}"/>
                    <h:outputText value="#{bundle.ViewProsjektKategorierLabel_kategoriNavn}"/>
                    <h:outputText value="#{prosjektKategorierController.selected.kategoriNavn}" title="#{bundle.ViewProsjektKategorierTitle_kategoriNavn}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{prosjektKategorierController.destroyAndView}" value="#{bundle.ViewProsjektKategorierDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewProsjektKategorierEditLink}"/>
                <br />
                <h:commandLink action="#{prosjektKategorierController.prepareCreate}" value="#{bundle.ViewProsjektKategorierCreateLink}" />
                <br />
                <h:commandLink action="#{prosjektKategorierController.prepareList}" value="#{bundle.ViewProsjektKategorierShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewProsjektKategorierIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>