src/java/server/entity/KontaktPersoner.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package server.entity;

import java.io.Serializable;
import java.util.Collection;
import java.util.logging.Logger;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Mikael
 */
@Entity
@Table(name = "KontaktPersoner")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "KontaktPersoner.findAll", query = "SELECT k FROM KontaktPersoner k"),
    @NamedQuery(name = "KontaktPersoner.findByIdPersoner", query = "SELECT k FROM KontaktPersoner k WHERE k.idPersoner = :idPersoner"),
    @NamedQuery(name = "KontaktPersoner.findByTittel", query = "SELECT k FROM KontaktPersoner k WHERE k.tittel = :tittel"),
    @NamedQuery(name = "KontaktPersoner.findByNavn", query = "SELECT k FROM KontaktPersoner k WHERE k.navn = :navn"),
    @NamedQuery(name = "KontaktPersoner.findByTlf", query = "SELECT k FROM KontaktPersoner k WHERE k.tlf = :tlf"),
    @NamedQuery(name = "KontaktPersoner.findByEpost", query = "SELECT k FROM KontaktPersoner k WHERE k.epost = :epost"),
    @NamedQuery(name = "KontaktPersoner.findByVersion", query = "SELECT k FROM KontaktPersoner k WHERE k.version > :version")})
public class KontaktPersoner implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = true)
    @Column(name = "idPersoner")
    private Integer idPersoner;
    @Size(max = 65)
    @Column(name = "Tittel")
    private String tittel;
    @Size(max = 65)
    @Column(name = "Navn")
    private String navn;
    @Size(max = 20)
    @Column(name = "Tlf")
    private String tlf;
    @Size(max = 65)
    @Column(name = "Epost")
    private String epost;
//    @JoinTable(name = "ProsjektKontakter", joinColumns = {
//        @JoinColumn(name = "KontaktPersoner_idPersoner", referencedColumnName = "idPersoner")}, inverseJoinColumns = {
//        @JoinColumn(name = "Prosjekter_ProsjektID", referencedColumnName = "ProsjektID")})
//    @ManyToMany(fetch = FetchType.LAZY, cascade=CascadeType.ALL )
//    private Collection<Prosjekter> prosjekterCollection;
    @ManyToMany(mappedBy = "kontaktPersonerCollection", fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    private Collection<Prosjekter> prosjekterCollection;
    @JoinColumn(name = "Firma_id", referencedColumnName = "idFirma")
    @ManyToOne(fetch = FetchType.LAZY)
    private Firma firmaid;
    @JoinColumn(name = "Adresse", referencedColumnName = "idAdresse" )
    @ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    private Adresse adresse;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "Version")
    private Double version;

    public Double getVersion() {
        return version;
    }

    public void setVersion(Double version) {
        this.version = version;
    }

    public KontaktPersoner() {
    }

    public KontaktPersoner(Integer idPersoner) {
        this.idPersoner = idPersoner;
    }

    public Integer getIdPersoner() {
        return idPersoner;
    }

    public void setIdPersoner(Integer idPersoner) {
        this.idPersoner = idPersoner;
    }

    public String getTittel() {
        return tittel;
    }

    public void setTittel(String tittel) {
        this.tittel = tittel;
    }

    public String getNavn() {
        return navn;
    }

    public void setNavn(String navn) {
        this.navn = navn;
    }

    public String getTlf() {
        return tlf;
    }

    public void setTlf(String tlf) {
        this.tlf = tlf;
    }

    public String getEpost() {
        return epost;
    }

    public void setEpost(String epost) {
        this.epost = epost;
    }

    @XmlTransient
    public Collection<Prosjekter> getProsjekterCollection() {
        return prosjekterCollection;
    }

    public void setProsjekterCollection(Collection<Prosjekter> prosjekterCollection) {
        this.prosjekterCollection = prosjekterCollection;
    }
    
    public void addProsjekter(Prosjekter prosjekt){
        this.prosjekterCollection.add(prosjekt);
    }
    
    public void removeProsjekter(Prosjekter prosjekt){
        this.prosjekterCollection.remove(prosjekt);
    }

    public Firma getFirmaid() {
        return firmaid;
    }

    public void setFirmaid(Firma firmaid) {
        this.firmaid = firmaid;
    }

    public Adresse getAdresse() {
        return adresse;
    }

    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idPersoner != null ? idPersoner.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof KontaktPersoner)) {
            return false;
        }
        KontaktPersoner other = (KontaktPersoner) object;
        if ((this.idPersoner == null && other.idPersoner != null) || (this.idPersoner != null && !this.idPersoner.equals(other.idPersoner))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return tittel + " " + navn;
    }
    private static final Logger LOG = Logger.getLogger(KontaktPersoner.class.getName());
    
}

src/java/server/web/KontaktPersonerController.java
package server.web;

import java.io.Serializable;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import server.ejb.AdresseFacade;
import server.ejb.KontaktPersonerFacade;
import server.entity.Adresse;
import server.entity.Firma;
import server.entity.KontaktPersoner;
import server.web.util.JsfUtil;
import server.web.util.PaginationHelper;
import server.web.util.SerializableListDataModel;

@ManagedBean(name = "kontaktPersonerController")
@SessionScoped
public class KontaktPersonerController implements Serializable {

    private KontaktPersoner current;
    private DataModel items = null;
    @EJB
    private server.ejb.KontaktPersonerFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private KontaktPersoner currentDialog;
    private ListDataModel allItems;
    
    private String adr1 = null;
    private String adr2 = null;
    private String adr3 = null;
    private Integer postNr = null;
    private String postSted = null;

    public String getAdr1() {
        return adr1;
    }

    public void setAdr1(String adr1) {
        this.adr1 = adr1;
    }

    public String getAdr2() {
        return adr2;
    }

    public void setAdr2(String adr2) {
        this.adr2 = adr2;
    }

    public String getAdr3() {
        return adr3;
    }

    public void setAdr3(String adr3) {
        this.adr3 = adr3;
    }

    public Integer getPostNr() {
        return postNr;
    }

    public void setPostNr(Integer postNr) {
        this.postNr = postNr;
    }

    public String getPostSted() {
        return postSted;
    }

    public void setPostSted(String postSted) {
        this.postSted = postSted;
    }
    
    //@EJB AdresseController aController;

    public KontaktPersoner getCurrentDialog() {
        return currentDialog;
    }

    public void setCurrentDialog(KontaktPersoner currentDialog) {
        this.currentDialog = currentDialog;
    }

    public KontaktPersonerController() {
    }

    public KontaktPersoner getSelected() {
        if (current == null) {
            current = new KontaktPersoner();
            selectedItemIndex = -1;
        }
        return current;
    }

    private KontaktPersonerFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public SerializableListDataModel createPageDataModel() {
                    return new SerializableListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "/kontaktPersoner/List";
    }
    public void prepareListAdd() {
        recreateModel();
    }

    public String prepareView() {
        current = (KontaktPersoner) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/kontaktPersoner/View";
    }
    

    public String prepareCreate() {
        current = new KontaktPersoner();
        selectedItemIndex = -1;
        return "/kontaktPersoner/List";
    }
    
    
    public void prepareCreateDialog() {
        adr1 = null;
        adr2 = null;
        adr3 = null;
        postNr = null;
        postSted = null;
        currentDialog = new KontaktPersoner();
        selectedItemIndex = -1;
       
    }

    public String create() {
        try {
            getFacade().create(currentDialog);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("KontaktPersonerCreated"));
            recreateModel();
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }
    @EJB AdresseFacade aFacade;
    public void createDialog() {
        Adresse adresse = new Adresse();
        adresse.setAdr1(adr1);
        adresse.setAdr2(adr2);
        adresse.setAdr3(adr3);
        adresse.setPostNr(postNr);
        adresse.setPostSted(postSted);
        //aFacade.create(adresse);
        currentDialog.setAdresse(adresse);
        try {
            getFacade().create(currentDialog);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("KontaktPersonerCreated"));
            recreateModel();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            
        }
    }

    public String prepareEdit() {
        current = (KontaktPersoner) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/kontaktPersoner/Edit";
    }

    public void prepareEditDialog(KontaktPersoner person) {
        currentDialog = person;
//        return "/kontaktPersoner/EditDialog";
    }

    public void updateDialog() {
        try {
            getFacade().edit(currentDialog);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("KontaktPersonerUpdated")));
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Database: ", ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured")));
        }
    }

    

    public String update() {
        try {
            getFacade().edit(current);
             FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("KontaktPersonerUpdated")));
            return "/kontaktPersoner/View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (KontaktPersoner) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "/kontaktPersoner/List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "/kontaktPersoner/View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "/kontaktPersoner/List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
             FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Database: ", ResourceBundle.getBundle("/Bundle").getString("KontaktPersonerDeleted")));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }
    
    public DataModel getAllItems(){
        return allItems = new ListDataModel(ejbFacade.findAll());
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "/kontaktPersoner/List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "/kontaktPersoner/List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public String getKontaktName(int id) {
        current = ejbFacade.find(id);
        return current.getNavn();
    }

    public String getFirmaNavn(Firma id) {
        return id.getFirmanavn();
    }

    @FacesConverter(forClass = KontaktPersoner.class)
    public static class KontaktPersonerControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }

web/kontaktPersoner/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.KontaktPersonerTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_tittel}" for="tittel" />
                    <h:inputText id="tittel" value="#{kontaktPersonerController.selected.tittel}" title="#{bundle.KontaktPersonerTitle_tittel}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_navn}" for="navn" />
                    <h:inputText id="navn" value="#{kontaktPersonerController.selected.navn}" title="#{bundle.KontaktPersonerTitle_navn}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_tlf}" for="tlf" />
                    <h:inputText id="tlf" value="#{kontaktPersonerController.selected.tlf}" title="#{bundle.KontaktPersonerTitle_tlf}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_epost}" for="epost" />
                    <h:inputText id="epost" value="#{kontaktPersonerController.selected.epost}" title="#{bundle.KontaktPersonerTitle_epost}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_firmaid}" for="firmaid" />
                    <h:selectOneMenu id="firmaid" value="#{kontaktPersonerController.selected.firmaid}" title="#{bundle.KontaktPersonerTitle_firmaid}" >
                        <f:selectItems value="#{firmaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_adresse}" for="adresse" />
                    <h:selectOneMenu id="adresse" value="#{kontaktPersonerController.selected.adresse}" title="#{bundle.KontaktPersonerTitle_adresse}" >
                        <f:selectItems value="#{adresseController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{kontaktPersonerController.create}" value="#{bundle.KontaktPersonerSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{kontaktPersonerController.prepareList}" value="#{bundle.KontaktPersonerShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.KontaktPersonerIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/kontaktPersoner/CreateKontaktperson.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:body>
        <h:panelGroup styleClass="dialogForm" layout="block">
            <h:form >
                <header>
                    <h2>
                        <h:outputText value="#{kontaktPersonerController.currentDialog.tittel} #{kontaktPersonerController.currentDialog.navn}"></h:outputText>
                    </h2>
                </header>
                <p:panelGrid columns="2" id="CreateDialog">
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_tittel}" for="tittel" />
                    <h:inputText id="tittel" value="#{kontaktPersonerController.currentDialog.tittel}" title="#{bundle.KontaktPersonerTitle_tittel}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_navn}" for="navn" />
                    <h:inputText id="navn" value="#{kontaktPersonerController.currentDialog.navn}" title="#{bundle.KontaktPersonerTitle_navn}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_tlf}" for="tlf" />
                    <h:inputText id="tlf" value="#{kontaktPersonerController.currentDialog.tlf}" title="#{bundle.KontaktPersonerTitle_tlf}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_epost}" for="epost" />
                    <h:inputText id="epost" value="#{kontaktPersonerController.currentDialog.epost}" title="#{bundle.KontaktPersonerTitle_epost}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_firmaid}" for="firmaid" />
                    <h:selectOneMenu id="firmaid" value="#{kontaktPersonerController.currentDialog.firmaid}" title="#{bundle.KontaktPersonerTitle_firmaid}" >
                        <f:selectItems value="#{firmaController.itemsAvailableSelectOne}" itemLabel="#{firmaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.AdresseLabel_adr1}" for="adr1" />
                    <h:inputText id="adr1" value="#{kontaktPersonerController.adr1}" title="#{bundle.AdresseTitle_adr1}" />
                    <h:outputLabel value="#{bundle.AdresseLabel_adr2}" for="adr2" />
                    <h:inputText id="adr2" value="#{kontaktPersonerController.adr2}" title="#{bundle.AdresseTitle_adr2}" />
                    <h:outputLabel value="#{bundle.AdresseLabel_adr3}" for="adr3" />
                    <h:inputText id="adr3" value="#{kontaktPersonerController.adr3}" title="#{bundle.AdresseTitle_adr3}" />
                    <h:outputLabel value="#{bundle.AdresseLabel_postNr}" for="postNr" />
                    <h:inputText id="postNr" value="#{kontaktPersonerController.postNr}" title="#{bundle.AdresseTitle_postNr}" />
                    <h:outputLabel value="#{bundle.AdresseLabel_postSted}" for="postSted" />
                    <h:inputText id="postSted" value="#{kontaktPersonerController.postSted}" title="#{bundle.AdresseTitle_postSted}" />  
                </p:panelGrid>
                <p:commandButton value="#{bundle.SaveLink}"
                                 id="submitButton"                                
                                 actionListener="#{kontaktPersonerController.createDialog}"
                                 update=":kontaktForm"
                                 oncomplete="createKontaktPersonDlg.hide()"
                                 />
                
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/kontaktPersoner/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.KontaktPersonerTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_tittel}" for="tittel" />
                    <h:inputText id="tittel" value="#{kontaktPersonerController.selected.tittel}" title="#{bundle.KontaktPersonerTitle_tittel}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_navn}" for="navn" />
                    <h:inputText id="navn" value="#{kontaktPersonerController.selected.navn}" title="#{bundle.KontaktPersonerTitle_navn}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_tlf}" for="tlf" />
                    <h:inputText id="tlf" value="#{kontaktPersonerController.selected.tlf}" title="#{bundle.KontaktPersonerTitle_tlf}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_epost}" for="epost" />
                    <h:inputText id="epost" value="#{kontaktPersonerController.selected.epost}" title="#{bundle.KontaktPersonerTitle_epost}" />
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_firmaid}" for="firmaid" />
                    <h:selectOneMenu id="firmaid" value="#{kontaktPersonerController.selected.firmaid}" title="#{bundle.KontaktPersonerTitle_firmaid}" >
                        <f:selectItems value="#{firmaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.KontaktPersonerLabel_adresse}" for="adresse" />
                    <h:selectOneMenu id="adresse" value="#{kontaktPersonerController.selected.adresse}" title="#{bundle.KontaktPersonerTitle_adresse}" >
                        <f:selectItems value="#{adresseController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>

                </h:panelGrid>
                <h:commandLink action="#{kontaktPersonerController.update}" value="#{bundle.KontaktPersonerSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.KontaktPersonerViewLink}"/>
                <br />
                <h:commandLink action="#{kontaktPersonerController.prepareList}" value="#{bundle.KontaktPersonerShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.KontaktPersonerIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/kontaktPersoner/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.KontaktPersonerTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <ui:include src="table.xhtml"></ui:include>
        </ui:define>
    </ui:composition>

</html>